apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  labels:
    {{- include "praporets.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/{{ .Values.analytics.database }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
