apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flag-edge
  labels:
    {{- include "praporets.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.flagEdge.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "praporets.selectorLabels" (dict "name" "flag-edge") | nindent 6 }}
